# 示例配置文件 config.yaml

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "user123"
  password: "password123"
  dbname: "my_database"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  debug: true

# 日志配置
log:
  level: "debug"
  file: "/var/log/myapp.log"
